### ISSUE TITLE
StrEnum class not available in python 3.10 

### ISSUE THREAD

**Issue by pwmarshall** [dahlb/carrier_api#21]
**Describe the bug**
Trying to run (a fork of) version 1.16.1 on python 3.10.12 and got ``ImportError: cannot import name 'StrEnum' from 'enum' (/usr/lib/python3.10/enum.py)``. 

I am running Ubuntu 22.04.5 LTS, and python 3.10 was just the default python version installed. 

Specifically this is only an error with the new HeatSourceTypes Enum defined in const.py. If there is a reason to keep it as a StrEnum and not just an default Enum, StrEnum was added in python3.11 and support for python3.10 could be dropped.

**Comment by dahlb** [comment]
v1.16.2 switches enum for the strenum because it was a simple change, but I generally only support the official HA container which is used by home assistant's OS.  I highly recommend using a container or ha os for improved stability and longevity.

HA's latest python package requires 3.11 [https://github.com/home-assistant/core/blob/af715a4b9a21a7c855afc67bec005d0e977c8987/pyproject.toml#L24]

and HA expects python 3.13 https://www.home-assistant.io/installation/linux#install-home-assistant-core
